travis:
  secure:
    BINSTAR_TOKEN: wLTk8m8X1NMw1Y7EBKLeeKxJ+KbfTmomd45YsgzibDQMAD6KrcrPoBA5dCs3hnHBhEOSOxnPR0bm9M1A3m6l8O57Ku+toGphCsSFRWlMqWr+1l4GGC4YZ/1qVXP+vcak3Moxs0YSMVMrCUfhbHddfLk7AV1B8E6ONMqU0wn96OI0FtZQNPz8zYXMSO7JathDhkEkIOe1eQnFJd3NqGAznzw9slJQ9upuVFKtpOKdZ1u0UMLad46k0AB8cqt0j0q3sS7VlGaebBeBxWc3TNA1QyJb7GBu7VSJRMhxCwHCVl00J09ixt5aLX2JqyO7yus/x99ADu2IzOCcFvbTCQXR052MdrtAbi3/v9DcLrmXaTvIX7aE8IsXIs74a05Aiw2raGmscLztg5K+CcLhYfgVZvNbtVavB5KWCtrZEqnUNV/KoiP+J2x1w8M/QCF2XCYf01xz7uDGGHmcGI9umzJ1ghse8kSUfcLg8H5ZFLARY4B37iNXTblGNLfWzLhbX9igFTNg7Dn9vZ1VZgQNeNcrdIeSRwOHviorn2OyRURdVUCbVurl50sVomTWvDq3e7Y172ljnFUHRTAAXYLrpmoWLdZKNLvaJriqslE4oW+U7HyzJB3DC/w65ZNmhxMyogUu9htAhlihTd31EDADgcJkdcLGvOZc1Pz9cblKxlHOZ6g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
